variable "vpc_cidr_block" {}
variable "subnet_cidr_block" {}
variable "avail_zone" {}
variable "env_prefix" {}
variable "allowed_ips" {}
variable "instance_type" {}
variable "public_key_location" {}
variable "private_key_location" {}
variable "image_name" {}